In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


In [2]:
# scaler tensor
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
scaler.item()

7

In [5]:
# vector tensor
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
tensor = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

In [14]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0704, 0.1725, 0.0810, 0.9905],
        [0.9174, 0.1511, 0.5289, 0.3774],
        [0.2885, 0.0854, 0.8197, 0.1317]])

In [15]:
random_tensor.ndim

2

In [16]:
random_tensor.shape

torch.Size([3, 4])

In [17]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
zeros = torch.zeros(3,4)
ones = torch.ones(3,4)

In [19]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
range_tensor = torch.arange(1,11,1)
range_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
ten_zoros = torch.zeros_like(range_tensor)
ten_zoros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype= None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [27]:
tensor*10

tensor([10, 20, 30])

In [28]:
tensor-10

tensor([-9, -8, -7])

In [29]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [30]:
# element wise multiplication
tensor*tensor

tensor([1, 4, 9])

In [31]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [32]:
tensor.shape

torch.Size([3])

In [33]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [35]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [36]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [37]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [38]:
x.argmax(),x.argmin()

(tensor(9), tensor(0))

In [39]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [40]:
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [41]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [42]:
z[:,0]=5
x,z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [43]:
x_stacked = torch.stack([x,x,x,x],dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [44]:
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [45]:
x_reshaped.shape

torch.Size([9, 1])

In [46]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
x_reshaped.squeeze().shape

torch.Size([9])

In [48]:
x_reshaped.unsqueeze(dim=0)

tensor([[[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [49]:
x_reshaped.unsqueeze(dim=0).shape

torch.Size([1, 9, 1])

In [50]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)

In [51]:
print(f'previous shape: {x_original.shape}')
print(f'new shape: {x_permuted.shape}')

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [52]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [53]:
x[0][0]

tensor([1, 2, 3])

In [54]:
x[:,0]

tensor([[1, 2, 3]])

In [55]:
x[:,:,1]

tensor([[2, 5, 8]])

In [56]:
x[:,2,2]

tensor([9])

In [57]:
x[0,:,2]

tensor([3, 6, 9])

In [58]:
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [59]:
array.dtype

dtype('float64')

In [60]:
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [61]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [62]:
torch.cuda.is_available()

False

In [63]:
torch.cuda.device_count()

0

In [64]:
tensor = torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [65]:
tensor_on_gpu = tensor.to('cuda')
tensor_on_gpu

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx